version: '3.8'

services:
  web:
    build:
      context: ./app
    ports:
      - "8000:5000"
    environment:
      FLASK_DEBUG: "True"
    networks:
      - app-network

  redis:
    image: redis:alpine
    volumes:
      - pr3-redis:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pr3-redis: