name: Run Tests

on:
  push:
    paths:
      - 'pr3/**'
  pull_request:
    paths:
      - 'pr3/**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./pr3
          file: ./pr3/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/python-flask-with-redis:latest
