name: Publish to dockerhub (pr3)

on:
  push:
    paths:
      - 'pr3/**'
  pull_request:
    paths:
      - 'pr3/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      attestations: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: dmitryqdocker/cicd-pr

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: ./pr3-4/app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
        

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/dmitryqdocker/cicd-pr
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true